name: "Data Pipeline - Parquet"
source:
  path: "resources/source_data_parquet"
  format: "parquet"
target:
  path: "resources/target_data_parquet"
  format: "parquet"
schema_check: false
data_reconciliation: true
