name: "Data Pipeline - CSV"
source:
  path: "source_data"
  format: "csv"
target:
  path: "target_data"
  format: "csv"
schema_check: true
row_count_check: true
data_reconciliation: true
checksum_check: true
